language: rust

cache: cargo

env:
  global:
    - TOOL=NONE

matrix:
  allow_failures:
    - rust: nightly
      env: TOOL=NONE
  fast_finish: true
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.39.0
    - rust: nightly
      env: TOOL=CLIPPY
      script: |
          rustup toolchain install nightly --allow-downgrade --component clippy
          cargo clippy
    - rust: nightly
      env: TOOL=FMT
      script: |
          rustup toolchain install nightly --allow-downgrade --component rustfmt
          cargo fmt

script:
- cargo build
- cargo test
- cargo doc --no-deps