language: rust
os: linux
cache: cargo

rust:
  - stable
  - beta
  - 1.39.0

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: nightly
    - rust: stable
      env: TOOL=CLIPPY
      script: |
          rustup component add clippy
          cargo clippy -- -D clippy::all
    - rust: stable
      env: TOOL=FMT
      script: |
          rustup component add rustfmt
          cargo fmt -- --check

script:
- cargo build
- cargo test
- cargo doc --no-deps