language: rust
os: linux
cache: cargo

rust:
  - stable
  - beta
  - nightly
  - 1.39.0

env:
  global:
    - TOOL=NONE

jobs:
  allow_failures:
    - rust: nightly
      env: TOOL=NONE
  fast_finish: true
  include:
    - rust: nightly
      env: TOOL=CLIPPY
      script: |
          rustup toolchain install nightly --allow-downgrade --component clippy
          cargo clippy
    - rust: nightly
      env: TOOL=FMT
      script: |
          rustup toolchain install nightly --allow-downgrade --component rustfmt
          cargo fmt

script:
- cargo build
- cargo test
- cargo doc --no-deps