language: rust

cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.39.0
    - rust: nightly
      env: CLIPPY
      script: |
          rustup toolchain install nightly --allow-downgrade --component clippy
          cargo clippy
    - rust: nightly
      env: FMT
      script: |
          rustup toolchain install nightly --allow-downgrade --component rustfmt
          cargo fmt

script:
- cargo build
- cargo test
- cargo doc --no-deps